### ISSUE TITLE
Support for Github Enterprise

### ISSUE THREAD

**Issue by tuxfight3r** [xthexder/wide-github#41] opened 2018-10-25 19:06 UTC
Can you update the logic for the domain to github.* so it would work with any github

**Comment by Martii** [comment] 2018-10-26 08:18
@tuxfight3r 
That would be a bit much I think... why not just use the .user.js engine to add the includes as you need them?

**Comment by xthexder** [comment] 2019-05-26 05:34
Closing as duplicate of #9

**Closed by xthexder** 2019-05-26 05:34 UTC
