### ISSUE TITLE
Not compatible with Octotree

### ISSUE THREAD

**Issue by mmalchuk** [xthexder/wide-github#31] opened 2018-03-26 07:25 UTC
Could you please fix the issue with https://github.com/buunguyen/octotree when the left panel is open?

**Comment by Martii** [comment] 2018-06-20 21:34
@mmalchuk 
Can you provide screenshots on what doesn't work for you. Seems to be working here.

Thanks.

**Comment by diimdeep** [comment] 2018-12-17 21:36
https://github.com/ovity/octotree/issues/497#issuecomment-390162540

**Comment by CollinChaffin** [comment] 2019-05-18 04:31
Also not working for me.  See my comments in the above mentioned #497.  Even when I manually change all to inherit, I'd say approx 75 percent of the time I too get the octotree overlapping bar.  If I click a file, go forward then back, or use their hotkey to contract and re-expand, it is fine but otherwise when using this userscript - pretty unusable.

What sucks is seperately, this userscript I've used for years and if I disable it, Octotree is also invaluable - they just don't like to play nice together. :(

Any help getting it fixed would be GREATLY appreciated!  TIA!

**Comment by CollinChaffin** [comment] 2019-05-19 06:40
Good news - I believe I have a working fix for this.  I have been testing for about an hour on repo after repo all different sections and went from a >90% failure rate of overlap to (after restarting Chrome and flushing cache cookies etc.) zero failures!

I will submit a PR shortly for you to check out.  Note this is ONLY for the UserScript version however the couple things I'm changing could easily be applied in the plugin as well.

**Comment by xthexder** [comment] 2019-05-20 20:30
I've never actually used Octotree before, but I just tried installing the Chrome extension, and it looks like there's no issues when using the Wide Github + Octotree chrome extensions.
I'll take a look at the userscript versions as well so they can be fixed.

**Comment by CollinChaffin** [comment] 2019-05-21 15:25
The injection is a bit different with the native extension whereas the userscript relies on Tampermonkey for injection, hence why my PR change is necessary.  If you read this issue and over at https://github.com/ovity/octotree/issues/497 you will see a ton of folks also having this issue - which my PR resolves if you merge it.  It also resolves the extra horizontal scrollbar which is due to padding when both are used together.

**Comment by xthexder** [comment] 2019-05-24 07:30
@CollinChaffin can you try and reproduce this again with the latest version?

With a fresh install of Octotree + Greasmonkey in Firefox and the latest Wide-Github I haven't seen the toolbar overlap any of the pages.
If the window is too narrow it will overlap still, but that's an issue with Octotree even without Wide-Github.

**Closed** 2019-05-26 05:32 UTC
